defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "mocov3-core50"
method: "mocov3"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 256
  pred_hidden_dim: 4096
  temperature: 0.1
momentum:
  base_tau: 0.996
  final_tau: 0.996
data:
  dataset: core50
  train_path: "/home/brothen/core50_arr.h5"  # Path to your H5 file
  val_path: None
  format: "h5"
  num_workers: 4
  dataset_kwargs:
    # Optionally specify which sessions to use (set to None to use all)
    # For standard Core50 train/test split, use sessions 1,2,4,5,6,8,9,11 for training
    backgrounds: ["s1", "s2", "s4", "s5", "s6", "s8", "s9", "s11"]  
optimizer:
  name: "lars"
  batch_size: 64
  lr: 1.6
  classifier_lr: 3e-3
  weight_decay: 1e-6
  no_labels: False  # Core50 has labels
scheduler:
  name: "warmup_cosine"
  warmup_epochs: 0.01
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
  keep_prev: True
  every_n_iter: 5000
auto_resume:
  enabled: True
# overwrite PL stuff
max_epochs: 100
devices: [0]  # Adjust based on available GPUs
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 32