defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "dino-vit-ego4d"
method: "dino"
backbone:
  name: "vit_base"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 256
  num_prototypes: 65536
  norm_last_layer: False
  warmup_teacher_temperature_epochs: 0
momentum:
  base_tau: 0.996
  final_tau: 0.996
  classifier: False
data:
  dataset: ego4d
  train_path: "/scratch/autolearn/aubret/ego4d/hdf5/"
  val_path: None
  format: "h5"
  num_workers: 8
  no_labels: True
  dataset_kwargs:
    gaze_size: 224
    time_window: 30
    center_crop: False #To compare gaze crop with a center crop with gaze size 540
    ego4d_subset: 1 #Ratio between 0 and 1

optimizer:
  name: "adamw"
  batch_size: 64
  lr: 0.0005
  classifier_lr: 3e-3
  weight_decay: 0.04
scheduler:
  name: "none"
  warmup_start_lr: 0
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
  keep_prev: True
  every_n_iter: 5000
auto_resume:
  enabled: True
  iter_sampler: True

# overwrite PL stuff
max_epochs: 1
devices: 8
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 32-true
no_validation: True
limit_val_batches: 0
num_sanity_val_steps: 0
val_check_interval: 5000
log_every_n_steps: 5000
