defaults:
  - _self_
  - augmentations: multicrop
  - wandb: ts_aubret
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "dino-vit_base-ego4d"
method: "dino"
backbone:
  name: "vit_base"
  kwargs:
    dynamic_img_size: True
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 256
  num_prototypes: 65536
  norm_last_layer: True
  use_bn_in_head: False

  student_temperature: 0.1
  teacher_temperature: 0.04
  warmup_teacher_temperature_epochs: 0
  warmup_teacher_temperature_steps: 0.0
momentum:
  base_tau: 0.996
  final_tau: 1.0
  classifier: False
data:
  dataset: ego4d
  train_path: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/shared/datasets/Ego4d/h5"
  val_path: None
  format: "h5"
  num_workers: 8
  no_labels: True
  dataset_kwargs:
    gaze_size: 224
    time_window: 15
    center_crop: False #To compare gaze crop with a center crop with gaze size 540
optimizer:
  name: "adamw"
  batch_size: 128
  lr: 0.0002
  classifier_lr: 3e-3
  weight_decay: 0.04
scheduler:
  name: "warmup_cosine"
  warmup_start_lr: 0.00001
  warmup_epochs: 0.05
  max_epochs: 1
  interval: "step"
checkpoint:
  enabled: True
  dir: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/schaumloeffel/logs/ego4d/"
  frequency: 1
  keep_prev: True
  every_n_iter: 5000
  save_last: True
auto_resume:
  enabled: False
  iter_sampler: True

# overwrite PL stuff
max_epochs: 1
devices: 5
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 32-true # 16-mixed 32-true
no_validation: True
limit_val_batches: 0
limit_train_batches: 1.0
num_sanity_val_steps: 0
val_check_interval: 0.1
log_every_n_steps: 100
