defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "linlast_mocov3nf_lr16_center_fullIN"
pretrained_feature_extractor: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/schaumloeffel/logs/ego4d/mocov3/iiiqnrs0/mocov3nf_lr16-iiiqnrs0-ep=last.ckpt"
classifier_ckpt: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/schaumloeffel/logs/ego4d/linear/sc7poe6z/linlast_mocov3nf_lr16_fullIN-sc7poe6z-ep=last.ckpt"

#pretrained_feature_extractor: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/schaumloeffel/logs/ego4d/mocov3/q9y4x1nm/mocov3nf_lr16_center-q9y4x1nm-ep=last.ckpt"
#classifier_ckpt: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/schaumloeffel/logs/ego4d/linear/kydllbtd/linlast_mocov3nf_lr16_center_fullIN-kydllbtd-ep=last.ckpt"

#pretrained_feature_extractor: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/schaumloeffel/logs/ego4d/mocov3/mocov3nf_lr16_gs540resize-mv0pnuza-ep=last.ckpt"
#classifier_ckpt: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/schaumloeffel/logs/ego4d/linear/3yo63ojk/linlast_mocov3nf_lr16_gs540resize_fullIN-3yo63ojk-ep=last.ckpt"

#pretrained_feature_extractor: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/schaumloeffel/logs/ego4d/mocov3/ba1e2na0/mocov3nf_lr16_gs540-ba1e2na0-ep=last.ckpt"
#classifier_ckpt: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/schaumloeffel/logs/ego4d/linear/nn14c1wf/linlast_mocov3nf_lr16_gs540_fullIN-nn14c1wf-ep=last.ckpt"

#pretrained_feature_extractor: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/schaumloeffel/logs/ego4d/mocov3/tlyydhj5/mocov3nf_lr16_gs336_t5-tlyydhj5-ep=last.ckpt"
#classifier_ckpt: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/schaumloeffel/logs/ego4d/linear/ijq07182/linlast_mocov3nf_lr16_gs336_t5_fullIN-ijq07182-ep=last.ckpt"


# t=5
#pretrained_feature_extractor: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/schaumloeffel/logs/ego4d/mocov3/mocov3nf_lr16t5-1qc1r931-ep=last.ckpt"
#classifier_ckpt: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/schaumloeffel/logs/ego4d/linear/linlast_mocov3nf_lr16t5_fullIN-my3lvfl5-ep=last.ckpt"

# t=10
#pretrained_feature_extractor: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/schaumloeffel/logs/ego4d/mocov3/mocov3nf_lr16t10-vpi2u0mn-ep=last.ckpt"
#classifier_ckpt: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/schaumloeffel/logs/ego4d/linear/linlast_mocov3nf_lr16t10_fullIN-rbh9et2s-ep=last.ckpt"


# t=0
#pretrained_feature_extractor: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/schaumloeffel/logs/ego4d/mocov3/mocov3nf_lr16t0-yboaa3by-ep=last.ckpt"
#classifier_ckpt: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/schaumloeffel/logs/ego4d/linear/linlast_mocov3nv_lr16t0_fullIN-e5wda4i8-ep=last.ckpt"

# t=20
#pretrained_feature_extractor: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/schaumloeffel/logs/ego4d/mocov3/mocov3nf_lr16t20-zd0jdcjy-ep=last.ckpt"
#classifier_ckpt: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/schaumloeffel/logs/ego4d/linear/linlast_mocov3nf_lr16t20_fullIN-5qvnd8r9-ep=last.ckpt"

backbone:
  name: "resnet50"
  kwargs: {}

pretrain_method: "mocov3"
data:
  dataset: ImageNet8
  path: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/shared/datasets/"
  num_workers: 8
  batch_size: 16

