defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "mocov3-core50-linear-eval"
backbone:
  name: "resnet18"
pretrained_feature_extractor: "trained_models/mocov3/ul71xpdw/mocov3-temporal-core50-ul71xpdw-ep=last-stp=last.ckpt"  # Update this path to your actual checkpoint
data:
  dataset: "core50"
  train_path: "/home/brothen/core50_arr.h5"
  val_path: "/home/brothen/core50_arr.h5"
  format: "h5"
  num_workers: 4
  train_backgrounds: ["s1", "s2", "s4", "s5", "s6", "s8", "s9", "s11"]  # train sessions
  val_backgrounds: ["s3", "s7", "s10"]  # test sessions
optimizer:
  name: "lars"
  batch_size: 64
  lr: 0.3
  weight_decay: 0
scheduler:
  name: "warmup_cosine"
  warmup_start_lr: 0.00001
  warmup_epochs: 0.0
  max_epochs: 100
  interval: "epoch"
checkpoint:
  enabled: True
  dir: "trained_models/linear"
  frequency: 1
grid:
  enabled: False
early_stopping:
  monitor: "val/loss"
  enabled: True
  patience: 5

pre_extract_feats: False
finetune: False
# extra training options
auto_resume:
  enabled: False
max_epochs: 100
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 32