defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "predify-moco-reconstruction-only-detached-reconstruction-gradients-vgg16"
method: "predify_moco"
backbone:
  name: "vgg16"
  #kwargs:
   # pretrained: True  
method_kwargs:
  # Standard MoCo parameters
  proj_hidden_dim: 4096
  proj_output_dim: 128
  pred_hidden_dim: 4096
  temperature: 0.1
  
  # Predictive coding parameters
  timesteps: 1  # Use 1 timestep for reconstruction-only mode
  pred_loss_weight: 1.0
  use_local_updates: true
  
  # PCoder gradient parameters
  enable_pcoder_grads: false  # Start with disabled for comparison
  pcoder_grad_scale: [0.05, 0.04, 0.03, 0.02, 0.01]  # Individual scaling factors for PCoder1-5 gradients
  
  # PCoder hyperparameters
  ffm: [0.4, 0.3, 0.2, 0.1, 0.1]
  fbm: [0.05, 0.05, 0.05, 0.0, 0.0]
  erm: [0.001, 0.001, 0.001, 0.001, 0.001]

momentum:
  base_tau: 0.99
  final_tau: 0.99

data:
  dataset: temporal_core50  
  train_path: "/home/brothen/core50_arr.h5"  
  val_path: "/home/brothen/core50_arr.h5"
  format: "h5"
  num_workers: 4
  dataset_kwargs:
    # Use standard Core50 train sessions
    backgrounds: ["s1", "s2", "s4", "s5", "s6", "s8", "s9", "s11"]
    val_backgrounds: ["s3", "s7", "s10"]  # Validation sessions
    time_window: 15 # Temporal offset window

optimizer:
  name: "lars"
  batch_size: 32
  lr: 0.12
  classifier_lr: 3e-3
  weight_decay: 1e-6
  no_labels: False  # Core50 has labels

scheduler:
  name: "warmup_cosine"
  warmup_epochs: 5
  min_lr: 0.0

checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
  keep_prev: True
  every_n_iter: 5000

auto_resume:
  enabled: False

# KNN evaluation callback config
knn_clb:
  enabled: True  # Disable KNN evaluation during training to prevent OOM
  dataset: "core50"  # Required even if disabled
  train_path: "/home/brothen/core50_arr.h5"
  val_path: "/home/brothen/core50_arr.h5"
  num_workers: 4
  batch_size: 64
  k: [10, 20, 50, 100]
  temperature: 0.07
  train_backgrounds: ["s1", "s2", "s4", "s5", "s6", "s8", "s9", "s11"]
  val_backgrounds: ["s3", "s7", "s10"]

# overwrite PL stuff
max_epochs: 200
devices: [0, 1, 2]  # Use GPUs 1, 2, and 3 (avoiding GPU 0)
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"  # Back to DDP for multi-GPU
precision: 32
#limit_train_batches: 5  # Only run 5 batches for debugging
#limit_val_batches: 5  # Only run 5 batches for debugging
# Validation settings
num_sanity_val_steps: 2  # Run 2 validation steps before training 