defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "difficulty_analysis_selective_curriculum"
method: "selective_curriculum_mocov3"  # Match your training method
backbone:
  name: "resnet18"

# Add ALL the method_kwargs that your model was trained with
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 256
  pred_hidden_dim: 4096
  temperature: 0.1
  
  # Curriculum learning parameters - MUST match training config
  curriculum_type: "jepa"
  curriculum_reverse: False
  curriculum_warmup_epochs: 10
  curriculum_weight: 1.0
  reconstruction_masking_ratio: 0.75
  
  # Selective curriculum parameters - MUST match training config
  num_candidates: 8
  curriculum_only_for_epochs: 100

# CRITICAL: Add the momentum section that was missing
momentum:
  base_tau: 0.996
  final_tau: 0.996

# Data configuration for evaluation - CHANGED from selective_temporal_core50 to core50_categories
data:
  dataset: "core50_categories"  # For difficulty analysis
  train_path: "/home/brothen/core50_arr.h5"
  val_path: "/home/brothen/core50_arr.h5"
  format: "h5"
  num_workers: 4
  dataset_kwargs:
    # Use standard Core50 train sessions
    backgrounds: ["s1", "s2", "s4", "s5", "s6", "s8", "s9", "s11"]
    val_backgrounds: ["s3", "s7", "s10"]  # Validation sessions
    time_window: 15  # Temporal offset window
    num_candidates: 8  # Number of temporal offsets to sample (match with method_kwargs)
    use_categories: True  # For difficulty evaluation

# Basic training parameters (needed for model initialization)
optimizer:
  name: "lars"
  batch_size: 64
  lr: 1.6
  classifier_lr: 3e-3
  weight_decay: 1e-6
  no_labels: False  # Core50 has labels

scheduler:
  name: "warmup_cosine"
  warmup_epochs: 0.01
  max_epochs: 100

checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 10
  keep_prev: True
  every_n_iter: 50000

auto_resume:
  enabled: False

knn_clb:
  enabled: False  # Disable for difficulty evaluation
  dataset: "core50"
  train_path: "/home/brothen/core50_arr.h5"
  val_path: "/home/brothen/core50_arr.h5"
  num_workers: 4
  batch_size: 64
  k: [10, 20, 50, 100]
  temperature: 0.07
  train_backgrounds: ["s1", "s2", "s4", "s5", "s6", "s8", "s9", "s11"]
  val_backgrounds: ["s3", "s7", "s10"]

# Additional parameters required by base model
no_validation: False  # Enable validation
accumulate_grad_batches: 1
log_every_n_steps: 50

# PL settings - CRITICAL: max_epochs at top level
max_epochs: 100
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp_find_unused_parameters_true"
precision: 32
num_sanity_val_steps: 2