defaults:
- _self_
name: difficulty_analysis_selective_curriculum
method: selective_curriculum_mocov3
backbone:
  name: resnet18
  kwargs: {}
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 256
  pred_hidden_dim: 4096
  temperature: 0.1
  curriculum_type: jepa
  curriculum_reverse: false
  curriculum_warmup_epochs: 20
  curriculum_weight: 1.0
  reconstruction_masking_ratio: 0.75
  num_candidates: 8
  curriculum_only_for_epochs: 100
  selection_epochs: 100
  base_tau_momentum: 0.996
  final_tau_momentum: 0.996
momentum:
  base_tau: 0.996
  final_tau: 0.996
data:
  dataset: core50_categories
  train_path: /home/brothen/core50_arr.h5
  val_path: /home/brothen/core50_arr.h5
  format: h5
  num_classes: 10
  num_workers: 4
  num_large_crops: 2
  num_small_crops: 0
  train_backgrounds:
  - s1
  - s2
  - s4
  - s5
  - s6
  - s8
  - s9
  - s11
  val_backgrounds:
  - s3
  - s7
  - s10
  dataset_kwargs:
    use_categories: true
  brightness: 0.4
  contrast: 0.4
  saturation: 0.2
  hue: 0.1
  color_jitter_prob: 0.8
  gray_scale_prob: 0.2
  horizontal_flip_prob: 0.5
  gaussian_prob: 1.0
  solarization_prob: 0.0
  crop_size: 224
  min_scale: 0.08
  max_scale: 1.0
optimizer:
  name: lars
  batch_size: 64
  lr: 1.6
  weight_decay: 1.0e-06
  momentum: 0.9
  eta: 0.02
  grad_clip_lars: false
  exclude_bias_n_norm: false
  classifier_lr: 0.3
scheduler:
  name: warmup_cosine
  warmup_epochs: 0.01
  warmup_start_lr: 0.0
  eta_min: 0.0
  max_epochs: 100
  interval: step
  frequency: 1
  lr_decay_steps: null
  min_lr: 0.0
  step_size: 30
  gamma: 0.1
loss:
  name: mocov3
  temperature: 0.1
max_epochs: 100
devices:
- 0
accelerator: gpu
precision: 32
sync_batchnorm: true
strategy: auto
enable_checkpointing: false
logger: false
callbacks: null
num_sanity_val_steps: 0
log_every_n_steps: 50
check_val_every_n_epoch: 1
accumulate_grad_batches: 1
no_validation: false
auto_resume: false
resume_from_checkpoint: null
augmentations: []
transform_kwargs: {}
auto_lr_find: false
fast_dev_run: false
overfit_batches: 0.0
track_grad_norm: -1
val_check_interval: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
limit_predict_batches: 1.0
