defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private_dino.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "dino-vit-imagenet"
method: "dino"
backbone:
  name: "vit_base"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 256
  num_prototypes: 65536
  norm_last_layer: True
momentum:
  base_tau: 0.99
  final_tau: 1.0
data:
  dataset: imagenet
  train_path: "./datasets/imagenet-100/train"
  val_path: "./datasets/imagenet-100/val"
  format: "dali"
  num_workers: 4
optimizer:
  name: "adamw"
  batch_size: 128
  lr: 0.005
  classifier_lr: 3e-3
  weight_decay: 0.04
scheduler:
  name: "none"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: 8
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 32
