defaults:
  - _self_
  - wandb: ts.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "dino-cifar100-linear-probe-augs"
pretrained_feature_extractor: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/schaumloeffel/logs/ego4d/dino/mqna241i/dino-vit-ego4d-mqna241i-ep=30000.ckpt"
backbone:
  name: "vit_base"
  kwargs:
    dynamic_img_size: True
method: "dino"
data:
  dataset: cifar100_224
  train_path: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/shared/datasets/"
  val_path: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/shared/datasets/"
  format: "image_folder"
  num_workers: 4
optimizer:
  name: "sgd"
  batch_size: 128
  lr: 0.2
  weight_decay: 0
scheduler:
  name: "step"
  lr_decay_steps: [60, 80]
checkpoint:
  enabled: True
  dir: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/schaumloeffel/logs/ego4d/"
  frequency: 1
  save_last: True
auto_resume:
  enabled: False


pre_extract_feats: False
finetune: False

# overwrite PL stuff
max_epochs: 100
devices: 8
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed
log_every_n_steps: 20
